version: "3.8"

services:
  goals_mongo:
    container_name: goals_mongo
    image: "mongo:5.0.0"
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    networks:
      - goals_net

  goals_backend:
    container_name: goals_backend
    image: goals_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # named volume
      - logs:/app/logs
      # bind volume
      - ./backend:/app
      # anonymous volume
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - goals_mongo
    networks:
      - goals_net

  goals_frontend:
    container_name: goals_frontend
    image: goals_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./env/frontend.env
    stdin_open: true
    tty: true
    depends_on:
      - goals_backend
    networks:
      - goals_net

volumes:
  data:
  logs:

networks:
  goals_net:
