version: "3.8"

services:
  node_express:
    container_name: node_express
    image: node_express
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      # named volume
      - logs:/app/logs
      # bind volume
      - ./app:/app
      # anonymous volume
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
  

volumes:
  logs: